export default {
    tenct: 'tenct',
    UserName: 'UserName',
    PassWord: 'PassWord',
    urlApi: 'urlApi',
    soDienThoai: 'soDienThoai',
    sip_user: 'sip_user',
    tennhanvien: 'tennhanvien',
    isLogin: 'isLogin',
    Registered: 'Registered',
    SessionCallId: 'SessionCallId',
    somayle: 'somayle',
    tendangnhap: 'tendangnhap',
    idnhanvien: 'idnhanvien',
    chucvu: 'chucvu',
    idct: 'idct',
    quyenGoiRa: 'quyenGoiRa',
    Prefix: 'Prefix',
    IncomingSignalData: 'IncomingSignalData',
    callid: 'callid',
    signalWebRTC: 'signalWebRTC',
    isAnswerCall: 'isAnswerCall',
}